name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv and requirements
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: uv sync --dev

      - name: Run Ruff Check
        run: uv run ruff check src/ tests/

      - name: Run Ruff Format Check
        run: uv run ruff format --check src/ tests/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv and requirements
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Run pytest
        run: uv run pytest -v

  docker:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./solutions/part1/1a-dockerfile/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:v1
